/* File: _libtaumodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Sat Nov 23 18:33:07 2013
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */
#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <string.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *_libtau_error;
static PyObject *_libtau_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef char * string;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
\
#define FAILNULL(p) do {                                            \
    if ((p) == NULL) {                                              \
        PyErr_SetString(PyExc_MemoryError, "NULL pointer found");   \
        goto capi_fail;                                             \
    }                                                               \
} while (0)

#define STRINGMALLOC(str,len)\
  if ((str = (string)malloc(sizeof(char)*(len+1))) == NULL) {\
    PyErr_SetString(PyExc_MemoryError, "out of memory");\
    goto capi_fail;\
  } else {\
    (str)[len] = '\0';\
  }

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (((PyArrayObject *)(capi_ ## var ## _tmp))->nd)
#define old_shape(var,dim) (((PyArrayObject *)(capi_ ## var ## _tmp))->dimensions[dim])
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define STRINGFREE(str) do {if (!(str == NULL)) free(str);} while (0)

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#define STRINGCOPYN(to,from,buf_size)                           \
    do {                                                        \
        int _m = (buf_size);                                    \
        char *_to = (to);                                       \
        char *_from = (from);                                   \
        FAILNULL(_to); FAILNULL(_from);                         \
        (void)strncpy(_to, _from, sizeof(char)*_m);             \
        _to[_m-1] = '\0';                                      \
        /* Padding with spaces instead of nulls */              \
        for (_m -= 2; _m >= 0 && _to[_m] == '\0'; _m--) {      \
            _to[_m] = ' ';                                      \
        }                                                       \
    } while (0)


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyFloat_Check(obj)) {
#ifdef __sgi
    *v = PyFloat_AsDouble(obj);
#else
    *v = PyFloat_AS_DOUBLE(obj);
#endif
    return 1;
  }
  tmp = PyNumber_Float(obj);
  if (tmp) {
#ifdef __sgi
    *v = PyFloat_AsDouble(tmp);
#else
    *v = PyFloat_AS_DOUBLE(tmp);
#endif
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = _libtau_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int string_from_pyobj(string *str,int *len,const string inistr,PyObject *obj,const char *errmess) {
  PyArrayObject *arr = NULL;
  PyObject *tmp = NULL;
#ifdef DEBUGCFUNCS
fprintf(stderr,"string_from_pyobj(str='%s',len=%d,inistr='%s',obj=%p)\n",(char*)str,*len,(char *)inistr,obj);
#endif
  if (obj == Py_None) {
    if (*len == -1)
      *len = strlen(inistr); /* Will this cause problems? */
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,inistr,*len+1);
    return 1;
  }
  if (PyArray_Check(obj)) {
    if ((arr = (PyArrayObject *)obj) == NULL)
      goto capi_fail;
    if (!ISCONTIGUOUS(arr)) {
      PyErr_SetString(PyExc_ValueError,"array object is non-contiguous.");
      goto capi_fail;
    }
    if (*len == -1)
      *len = (arr->descr->elsize)*PyArray_SIZE(arr);
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,arr->data,*len+1);
    return 1;
  }
  if (PyString_Check(obj)) {
    tmp = obj;
    Py_INCREF(tmp);
  }
#if PY_VERSION_HEX >= 0x03000000
  else if (PyUnicode_Check(obj)) {
    tmp = PyUnicode_AsASCIIString(obj);
  }
  else {
    PyObject *tmp2;
    tmp2 = PyObject_Str(obj);
    if (tmp2) {
      tmp = PyUnicode_AsASCIIString(tmp2);
      Py_DECREF(tmp2);
    }
    else {
      tmp = NULL;
    }
  }
#else
  else {
    tmp = PyObject_Str(obj);
  }
#endif
  if (tmp == NULL) goto capi_fail;
  if (*len == -1)
    *len = PyString_GET_SIZE(tmp);
  STRINGMALLOC(*str,*len);
  STRINGCOPYN(*str,PyString_AS_STRING(tmp),*len+1);
  Py_DECREF(tmp);
  return 1;
capi_fail:
  Py_XDECREF(tmp);
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = _libtau_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int float_from_pyobj(float* v,PyObject *obj,const char *errmess) {
  double d=0.0;
  if (double_from_pyobj(&d,obj,errmess)) {
    *v = (float)d;
    return 1;
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(ttimes,TTIMES)(float*,float*,string,string*,float*,float*,float*,float*,float*,size_t);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/*********************************** ttimes ***********************************/
static char doc_f2py_rout__libtau_ttimes[] = "\
phcd,tt,toang,dtdd,dtdh,dddp = ttimes(deltain,zs,modnam)\n\nWrapper for ``ttimes``.\
\n\nParameters\n----------\n"
"deltain : input float\n"
"zs : input float\n"
"modnam : input string(len=500)\n"
"\nReturns\n-------\n"
"phcd : rank-2 array('S') with bounds (60,8)\n"
"tt : rank-1 array('f') with bounds (60)\n"
"toang : rank-1 array('f') with bounds (60)\n"
"dtdd : rank-1 array('f') with bounds (60)\n"
"dtdh : rank-1 array('f') with bounds (60)\n"
"dddp : rank-1 array('f') with bounds (60)";
/* extern void F_FUNC(ttimes,TTIMES)(float*,float*,string,string*,float*,float*,float*,float*,float*,size_t); */
static PyObject *f2py_rout__libtau_ttimes(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*,string,string*,float*,float*,float*,float*,float*,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float deltain = 0;
  PyObject *deltain_capi = Py_None;
  float zs = 0;
  PyObject *zs_capi = Py_None;
  string modnam = NULL;
  int slen(modnam);
  PyObject *modnam_capi = Py_None;
  string *phcd = NULL;
  npy_intp phcd_Dims[2] = {-1, -1};
  const int phcd_Rank = 2;
  PyArrayObject *capi_phcd_tmp = NULL;
  int capi_phcd_intent = 0;
  float *tt = NULL;
  npy_intp tt_Dims[1] = {-1};
  const int tt_Rank = 1;
  PyArrayObject *capi_tt_tmp = NULL;
  int capi_tt_intent = 0;
  float *toang = NULL;
  npy_intp toang_Dims[1] = {-1};
  const int toang_Rank = 1;
  PyArrayObject *capi_toang_tmp = NULL;
  int capi_toang_intent = 0;
  float *dtdd = NULL;
  npy_intp dtdd_Dims[1] = {-1};
  const int dtdd_Rank = 1;
  PyArrayObject *capi_dtdd_tmp = NULL;
  int capi_dtdd_intent = 0;
  float *dtdh = NULL;
  npy_intp dtdh_Dims[1] = {-1};
  const int dtdh_Rank = 1;
  PyArrayObject *capi_dtdh_tmp = NULL;
  int capi_dtdh_intent = 0;
  float *dddp = NULL;
  npy_intp dddp_Dims[1] = {-1};
  const int dddp_Rank = 1;
  PyArrayObject *capi_dddp_tmp = NULL;
  int capi_dddp_intent = 0;
  static char *capi_kwlist[] = {"deltain","zs","modnam",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO:_libtau.ttimes",\
    capi_kwlist,&deltain_capi,&zs_capi,&modnam_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable dddp */
  dddp_Dims[0]=60;
  capi_dddp_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_dddp_tmp = array_from_pyobj(NPY_FLOAT,dddp_Dims,dddp_Rank,capi_dddp_intent,Py_None);
  if (capi_dddp_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_libtau_error,"failed in converting hidden `dddp' of _libtau.ttimes to C/Fortran array" );
  } else {
    dddp = (float *)(capi_dddp_tmp->data);

  /* Processing variable phcd */
  phcd_Dims[0]=60,phcd_Dims[1]=8;
  capi_phcd_intent |= F2PY_INTENT_C|F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_phcd_tmp = array_from_pyobj(NPY_CHAR,phcd_Dims,phcd_Rank,capi_phcd_intent,Py_None);
  if (capi_phcd_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_libtau_error,"failed in converting hidden `phcd' of _libtau.ttimes to C/Fortran array" );
  } else {
    phcd = (string *)(capi_phcd_tmp->data);

  /* Processing variable dtdd */
  dtdd_Dims[0]=60;
  capi_dtdd_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_dtdd_tmp = array_from_pyobj(NPY_FLOAT,dtdd_Dims,dtdd_Rank,capi_dtdd_intent,Py_None);
  if (capi_dtdd_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_libtau_error,"failed in converting hidden `dtdd' of _libtau.ttimes to C/Fortran array" );
  } else {
    dtdd = (float *)(capi_dtdd_tmp->data);

  /* Processing variable modnam */
  slen(modnam) = 500;
  f2py_success = string_from_pyobj(&modnam,&slen(modnam),"",modnam_capi,"string_from_pyobj failed in converting 3rd argument `modnam' of _libtau.ttimes to C string");
  if (f2py_success) {
  /* Processing variable dtdh */
  dtdh_Dims[0]=60;
  capi_dtdh_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_dtdh_tmp = array_from_pyobj(NPY_FLOAT,dtdh_Dims,dtdh_Rank,capi_dtdh_intent,Py_None);
  if (capi_dtdh_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_libtau_error,"failed in converting hidden `dtdh' of _libtau.ttimes to C/Fortran array" );
  } else {
    dtdh = (float *)(capi_dtdh_tmp->data);

  /* Processing variable tt */
  tt_Dims[0]=60;
  capi_tt_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_tt_tmp = array_from_pyobj(NPY_FLOAT,tt_Dims,tt_Rank,capi_tt_intent,Py_None);
  if (capi_tt_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_libtau_error,"failed in converting hidden `tt' of _libtau.ttimes to C/Fortran array" );
  } else {
    tt = (float *)(capi_tt_tmp->data);

  /* Processing variable toang */
  toang_Dims[0]=60;
  capi_toang_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_toang_tmp = array_from_pyobj(NPY_FLOAT,toang_Dims,toang_Rank,capi_toang_intent,Py_None);
  if (capi_toang_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_libtau_error,"failed in converting hidden `toang' of _libtau.ttimes to C/Fortran array" );
  } else {
    toang = (float *)(capi_toang_tmp->data);

  /* Processing variable deltain */
    f2py_success = float_from_pyobj(&deltain,deltain_capi,"_libtau.ttimes() 1st argument (deltain) can't be converted to float");
  if (f2py_success) {
  /* Processing variable zs */
    f2py_success = float_from_pyobj(&zs,zs_capi,"_libtau.ttimes() 2nd argument (zs) can't be converted to float");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&deltain,&zs,modnam,phcd,tt,toang,dtdd,dtdh,dddp,slen(modnam));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NNNNNN",capi_phcd_tmp,capi_tt_tmp,capi_toang_tmp,capi_dtdd_tmp,capi_dtdh_tmp,capi_dddp_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of zs*/
  /* End of cleaning variable zs */
  } /*if (f2py_success) of deltain*/
  /* End of cleaning variable deltain */
  }  /*if (capi_toang_tmp == NULL) ... else of toang*/
  /* End of cleaning variable toang */
  }  /*if (capi_tt_tmp == NULL) ... else of tt*/
  /* End of cleaning variable tt */
  }  /*if (capi_dtdh_tmp == NULL) ... else of dtdh*/
  /* End of cleaning variable dtdh */
    STRINGFREE(modnam);
  }  /*if (f2py_success) of modnam*/
  /* End of cleaning variable modnam */
  }  /*if (capi_dtdd_tmp == NULL) ... else of dtdd*/
  /* End of cleaning variable dtdd */
  }  /*if (capi_phcd_tmp == NULL) ... else of phcd*/
  /* End of cleaning variable phcd */
  }  /*if (capi_dddp_tmp == NULL) ... else of dddp*/
  /* End of cleaning variable dddp */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of ttimes *******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"ttimes",-1,{{-1}},0,(char *)F_FUNC(ttimes,TTIMES),(f2py_init_func)f2py_rout__libtau_ttimes,doc_f2py_rout__libtau_ttimes},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "_libtau",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit__libtau(void) {
#else
#define RETVAL
PyMODINIT_FUNC init_libtau(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = _libtau_module = PyModule_Create(&moduledef);
#else
  m = _libtau_module = Py_InitModule("_libtau", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module _libtau (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module '_libtau' is auto-generated with f2py (version:2).\nFunctions:\n"
"  phcd,tt,toang,dtdd,dtdh,dddp = ttimes(deltain,zs,modnam)\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  _libtau_error = PyErr_NewException ("_libtau.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));

/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"_libtau");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
